// Generated by pdast2mozzi — do not edit
// Adjust MOZZI_CONTROL_RATE below to taste before compiling.
#define MOZZI_CONTROL_RATE 64
#define MOZZI_AUDIO_CHANNELS MOZZI_STEREO
#include <Mozzi.h>
#include <Oscil.h>
#include <tables/sin2048_int8.h>
#include <math.h>
#include <stdint.h>

#define PD_MSG_MAX 8
#define PD_MAX_DEPTH 64

typedef struct { int len; float a[PD_MSG_MAX]; } PdMsg;

static inline PdMsg pd_msg_bang(void) { PdMsg m; m.len = 0; return m; }
static inline PdMsg pd_msg_f(float v) { PdMsg m; m.len = 1; m.a[0] = v; return m; }

static int pd_depth __attribute__((unused)) = 0;

// ── unit generator instances ──────────────────────────────
Oscil<SIN2048_NUM_CELLS, MOZZI_AUDIO_RATE> pd_osc_n3(SIN2048_DATA);

// ── node state ────────────────────────────────────────────
float pd_n0;
uint32_t pd_n0_phase;
int32_t pd_n1;
int32_t pd_n2;
int32_t pd_n3;
int32_t pd_n4;


void setup() {
  startMozzi();
pd_n0 = 0.0f; pd_n0_phase = 0;
pd_n1 = 0;
pd_n2 = 0;
pd_n3 = 0;
pd_n4 = 0;
}

void updateControl() {
}

AudioOutput updateAudio() {
  { float _fr = (float)(5.0f); uint32_t _inc = (uint32_t)((_fr / (float)MOZZI_AUDIO_RATE) * 4294967296.0f); pd_n0_phase += _inc; pd_n0 = (float)pd_n0_phase / 4294967296.0f; }
  pd_n1 = (int32_t)(((float)(pd_n0)) * ((float)(20.0f)));
  pd_n2 = (int32_t)(((float)(pd_n1)) + ((float)(440.0f)));
  pd_osc_n3.setFreq((float)(pd_n2)); pd_n3 = pd_osc_n3.next();
  pd_n4 = (int32_t)(((float)(pd_n3)) * ((float)(0.5f)));
  return StereoOutput::fromNBit(9, constrain((int32_t)(pd_n4), -256, 255), constrain((int32_t)(pd_n4), -256, 255));
}

void loop() {
  audioHook();
}

// ── pd_* hooks: call these from your own MIDI library / pot-reading code ──
void pd_note_on(byte note, byte velocity) {
  (void)note; (void)velocity;
}

void pd_note_off(byte note, byte velocity) {
  (void)note; (void)velocity;
}

void pd_control_change(byte controller, byte value) {
  (void)controller; (void)value;
}

void pd_pitch_bend(int value) {
  (void)value;
}

void pd_touch(byte value) {
  (void)value;
}

void pd_program_change(byte value) {
  (void)value;
}

void pd_set_param(int index, float value) {
  switch (index) {
    default: break;
  }
}

float pd_get_param(int index) {
  switch (index) {
    default: return 0.0f;
  }
}

struct PdParamInfo { const char* name; float min; float max; float default_value; };
const int PD_NUM_PARAMS = 0;
const PdParamInfo PD_PARAMS[] = {
  { "", 0, 0, 0 }, // unused: PD_NUM_PARAMS is 0
};
